//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.VoucherShop.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Credits = new HashSet<Credit>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public bool Paid { get; set; }
        public long Amount { get; set; }
        public System.DateTime BankConfDate { get; set; }
        public int BankStatus { get; set; }
    
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
