//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.VoucherShop.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.ACLs = new HashSet<ACL>();
        }
    
        public long Id { get; set; }
        public string FriendlyName { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public string InputParameters { get; set; }
        public byte Division { get; set; }
    
        public virtual ICollection<ACL> ACLs { get; set; }
    }
}
