//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.VoucherShop.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public string Name { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
